use std::fmt;
use rand::{seq::SliceRandom, thread_rng};
use bevy::prelude::*;

pub fn random_suffix() -> Suffix {
    let mut rng = thread_rng();
    *SUFFIXES.choose(&mut rng).unwrap()
}

pub fn random_prefix() -> Prefix {
    let mut rng = thread_rng();
    *PREFIXES.choose(&mut rng).unwrap()
}

#[derive(Debug, PartialEq, Eq, Hash)]
enum SpecialSuffix {
    Kit,
    Paw,
    Star,
}

#[derive(Debug, Copy, Clone, Component)]
pub enum Suffix {
    Fur, Tuft, Tooth, Pelt, Tail, Claw, Foot, Whisker, Heart, Arch, Ash, Aster, Back, Badger, Bark, Bat, Beak, Beam, Bee,
    Beetle, Bellow, Belly, Berry, Billow, Bird, Bite, Blaze, Blink, Bloom, Blossom, Blotch, Blur, Bone, Bounce, Bracken,
    Bramble, Branch, Break, Breeze, Briar, Bright, Brook, Bubble, Bud, Bumble, Burn, Burr, Burst, Bush, Buzz, Call, Catcher,
    Chase, Chaser, Chasm, Chest, Chill, Chirp, Chomp, Cinder, Clash, Cloud, Clover, Crackle, Crash, Crawl, Creek, Crest, Cry,
    Curl, Current, Daisy, Dance, Dapple, Dart, Dash, Dawn, Daze, Dazzle, Dew, Dream, Drift, Drizzle, Drop, Dusk, Dust, Eagle,
    Ear, Ears, Echo, Egg, Ember, Eye, Eyes, Face, Falcon, Fall, Fang, Feather, Fern, Fin, Fire, Fish, Flake, Flame, Flare,
    Flash, Fleck, Flick, Flicker, Flight, Flip, Flit, Flood, Flow, Flower, Fluff, Fog, Fox, Freeze, Frost, Fruit, Fuzz, Gale,
    Gaze, Ghost, Glare, Gleam, Glide, Glint, Goose, Gorse, Grass, Growl, Hail, Hare, Haven, Hawk, Haze, Heather, Hiss, Hollow,
    Holly, Honey, Hope, Howl, Husk, Ice, Iris, Ivy, Jaw, Jay, Joy, Jumble, Jump, Kestrel, Kick, Kite, Knoll, Lake, Larch, Laurel,
    Leaf, Leap, Leg, Leopard, Light, Lightning, Lilac, Lily, Lion, Lotus, Mallow, Mane, Mark, Mask, Meadow, Mimic, Minnow, Mist,
    Moon, Moor, Moss, Moth, Mouse, Munch, Murk, Muzzle, Needle, Nest, Nettle, Newt, Nibble, Night, Nip, Noise, Nose, Nudge, Nut,
    Pad, Patch, Path, Peak, Petal, Plume, Pond, Pool, Poppy, Pounce, Prance, Prickle, Puddle, Purr, Quill, Quiver, Rain, Rapid,
    Raven, Reed, Rip, Ripple, Rise, River, Roach, Roar, Rock, Root, Rose, Rumble, Rump, Run, Runner, Rush, Rustle, Scar, Scratch,
    Screech, Seed, Seeker, Shade, Shadow, Shard, Shell, Shimmer, Shine, Shiver, Shock, Shriek, Sight, Silk, Skip, Skitter, Sky,
    Slash, Slip, Snap, Snarl, Snout, Snow, Soar, Song, Spark, Speck, Speckle, Spider, Spike, Spirit, Splash, Splinter, Spore, Spot,
    Spots, Spring, Sprout, Stalk, Stem, Step, Sting, Stone, Storm, Streak, Stream, Strike, Stripe, Sun, Swarm, Swipe, Swoop,
    Talon, Tangle, Thistle, Thorn, Thrift, Throat, Thrush, Thud, Thunder, Tiger, Timber, Toe, Trail, Tree, Trot, Tumble,
    Twist, Valley, Watcher, Water, Wave, Web, Whisper, Whistle, Willow, Wind, Wing, Wish, Wisp, Zoom,
}



pub const SUFFIXES: &[Suffix] = &[
    Suffix::Fur, Suffix::Fur, Suffix::Fur, Suffix::Fur, Suffix::Fur, Suffix::Fur, Suffix::Fur, Suffix::Fur, Suffix::Fur, Suffix::Fur, 
    Suffix::Fur, Suffix::Tuft, Suffix::Tuft, Suffix::Tuft, Suffix::Tuft, Suffix::Tuft, Suffix::Tooth, Suffix::Tooth, Suffix::Tooth, 
    Suffix::Tooth, Suffix::Tooth, Suffix::Pelt, Suffix::Pelt, Suffix::Pelt, Suffix::Pelt, Suffix::Pelt, Suffix::Pelt, Suffix::Pelt, 
    Suffix::Pelt, Suffix::Pelt, Suffix::Pelt, Suffix::Pelt, Suffix::Tail, Suffix::Tail, Suffix::Tail, Suffix::Tail, Suffix::Tail, 
    Suffix::Tail, Suffix::Tail, Suffix::Claw, Suffix::Claw, Suffix::Claw, Suffix::Claw, Suffix::Claw, Suffix::Claw, Suffix::Foot, 
    Suffix::Foot, Suffix::Foot, Suffix::Foot, Suffix::Foot, Suffix::Whisker, Suffix::Whisker, Suffix::Whisker, Suffix::Whisker, 
    Suffix::Whisker, Suffix::Whisker, Suffix::Heart, Suffix::Heart, Suffix::Heart, Suffix::Heart, Suffix::Heart, Suffix::Heart, 
    Suffix::Heart, Suffix::Heart, Suffix::Arch, Suffix::Ash, Suffix::Aster, Suffix::Back, Suffix::Badger, Suffix::Bark, Suffix::Bat, 
    Suffix::Beak, Suffix::Beam, Suffix::Bee, Suffix::Beetle, Suffix::Bellow, Suffix::Belly, Suffix::Berry, Suffix::Billow, Suffix::Bird, 
    Suffix::Bite, Suffix::Blaze, Suffix::Blink, Suffix::Bloom, Suffix::Blossom, Suffix::Blotch, Suffix::Blur, Suffix::Bone, Suffix::Bounce, 
    Suffix::Bracken, Suffix::Bramble, Suffix::Branch, Suffix::Break, Suffix::Breeze, Suffix::Briar, Suffix::Bright, Suffix::Brook, 
    Suffix::Bubble, Suffix::Bud, Suffix::Bumble, Suffix::Burn, Suffix::Burr, Suffix::Burst, Suffix::Bush, Suffix::Buzz, Suffix::Call, 
    Suffix::Catcher, Suffix::Chase, Suffix::Chaser, Suffix::Chasm, Suffix::Chest, Suffix::Chill, Suffix::Chirp, Suffix::Chomp, 
    Suffix::Cinder, Suffix::Clash, Suffix::Cloud, Suffix::Clover, Suffix::Crackle, Suffix::Crash, Suffix::Crawl, Suffix::Creek, 
    Suffix::Crest, Suffix::Cry, Suffix::Curl, Suffix::Current, Suffix::Daisy, Suffix::Dance, Suffix::Dapple, Suffix::Dart, Suffix::Dash, 
    Suffix::Dawn, Suffix::Daze, Suffix::Dazzle, Suffix::Dew, Suffix::Dream, Suffix::Drift, Suffix::Drizzle, Suffix::Drop, Suffix::Dusk, 
    Suffix::Dust, Suffix::Eagle, Suffix::Ear, Suffix::Ears, Suffix::Echo, Suffix::Egg, Suffix::Ember, Suffix::Eye, Suffix::Eyes, Suffix::Face, 
    Suffix::Falcon, Suffix::Fall, Suffix::Fang, Suffix::Feather, Suffix::Fern, Suffix::Fin, Suffix::Fire, Suffix::Fish, Suffix::Flake, 
    Suffix::Flame, Suffix::Flare, Suffix::Flash, Suffix::Fleck, Suffix::Flick, Suffix::Flicker, Suffix::Flight, Suffix::Flip, Suffix::Flit, 
    Suffix::Flood, Suffix::Flow, Suffix::Flower, Suffix::Fluff, Suffix::Fog, Suffix::Fox, Suffix::Freeze, Suffix::Frost, Suffix::Fruit, 
    Suffix::Fuzz, Suffix::Gale, Suffix::Gaze, Suffix::Ghost, Suffix::Glare, Suffix::Gleam, Suffix::Glide, Suffix::Glint, Suffix::Goose, 
    Suffix::Gorse, Suffix::Grass, Suffix::Growl, Suffix::Hail, Suffix::Hare, Suffix::Haven, Suffix::Hawk, Suffix::Haze, Suffix::Heather, 
    Suffix::Hiss, Suffix::Hollow, Suffix::Holly, Suffix::Honey, Suffix::Hope, Suffix::Howl, Suffix::Husk, Suffix::Ice, Suffix::Iris, 
    Suffix::Ivy, Suffix::Jaw, Suffix::Jay, Suffix::Joy, Suffix::Jumble, Suffix::Jump, Suffix::Kestrel, Suffix::Kick, Suffix::Kite, 
    Suffix::Knoll, Suffix::Lake, Suffix::Larch, Suffix::Laurel, Suffix::Leaf, Suffix::Leap, Suffix::Leg, Suffix::Leopard, Suffix::Light, 
    Suffix::Lightning, Suffix::Lilac, Suffix::Lily, Suffix::Lion, Suffix::Lotus, Suffix::Mallow, Suffix::Mane, Suffix::Mark, Suffix::Mask, 
    Suffix::Meadow, Suffix::Mimic, Suffix::Minnow, Suffix::Mist, Suffix::Moon, Suffix::Moor, Suffix::Moss, Suffix::Moth, Suffix::Mouse, 
    Suffix::Munch, Suffix::Murk, Suffix::Muzzle, Suffix::Needle, Suffix::Nest, Suffix::Nettle, Suffix::Newt, Suffix::Nibble, Suffix::Night, 
    Suffix::Nip, Suffix::Noise, Suffix::Nose, Suffix::Nudge, Suffix::Nut, Suffix::Pad, Suffix::Patch, Suffix::Path, Suffix::Peak, Suffix::Petal, 
    Suffix::Plume, Suffix::Pond, Suffix::Pool, Suffix::Poppy, Suffix::Pounce, Suffix::Prance, Suffix::Prickle, Suffix::Puddle, Suffix::Purr, 
    Suffix::Quill, Suffix::Quiver, Suffix::Rain, Suffix::Rapid, Suffix::Raven, Suffix::Reed, Suffix::Rip, Suffix::Ripple, Suffix::Rise, 
    Suffix::River, Suffix::Roach, Suffix::Roar, Suffix::Rock, Suffix::Root, Suffix::Rose, Suffix::Rumble, Suffix::Rump, Suffix::Run, 
    Suffix::Runner, Suffix::Rush, Suffix::Rustle, Suffix::Scar, Suffix::Scratch, Suffix::Screech, Suffix::Seed, Suffix::Seeker, Suffix::Shade, 
    Suffix::Shadow, Suffix::Shard, Suffix::Shell, Suffix::Shimmer, Suffix::Shine, Suffix::Shiver, Suffix::Shock, Suffix::Shriek, Suffix::Sight, 
    Suffix::Silk, Suffix::Skip, Suffix::Skitter, Suffix::Sky, Suffix::Slash, Suffix::Slip, Suffix::Snap, Suffix::Snarl, Suffix::Snout, Suffix::Snow, 
    Suffix::Soar, Suffix::Song, Suffix::Spark, Suffix::Speck, Suffix::Speckle, Suffix::Spider, Suffix::Spike, Suffix::Spirit, Suffix::Splash, 
    Suffix::Splinter, Suffix::Spore, Suffix::Spot, Suffix::Spots, Suffix::Spring, Suffix::Sprout, Suffix::Stalk, Suffix::Stem, Suffix::Step, 
    Suffix::Sting, Suffix::Stone, Suffix::Storm, Suffix::Streak, Suffix::Stream, Suffix::Strike, Suffix::Stripe, Suffix::Sun, Suffix::Swarm, 
    Suffix::Swipe, Suffix::Swoop, Suffix::Talon, Suffix::Tangle, Suffix::Thistle, Suffix::Thorn, Suffix::Thrift, Suffix::Throat, Suffix::Thrush, Suffix::Thud, Suffix::Thunder, Suffix::Tiger, Suffix::Timber, 
    Suffix::Toe, Suffix::Tooth, Suffix::Trail, Suffix::Tree, Suffix::Trot, Suffix::Tumble, Suffix::Twist, Suffix::Valley, Suffix::Watcher, 
    Suffix::Water, Suffix::Wave, Suffix::Web, Suffix::Whisper, Suffix::Whistle, Suffix::Willow, Suffix::Wind, Suffix::Wing, Suffix::Wish, 
    Suffix::Wisp, Suffix::Zoom,
];

impl fmt::Display for Suffix {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let suffix_str = match self {
            Suffix::Fur => "fur",
            Suffix::Tuft => "tuft",
            Suffix::Tooth => "tooth",
            Suffix::Pelt => "pelt",
            Suffix::Tail => "tail",
            Suffix::Claw => "claw",
            Suffix::Foot => "foot",
            Suffix::Whisker => "whisker",
            Suffix::Heart => "heart",
            Suffix::Arch => "arch",
            Suffix::Ash => "ash",
            Suffix::Aster => "aster",
            Suffix::Back => "back",
            Suffix::Badger => "badger",
            Suffix::Bark => "bark",
            Suffix::Bat => "bat",
            Suffix::Beak => "beak",
            Suffix::Beam => "beam",
            Suffix::Bee => "bee",
            Suffix::Beetle => "beetle",
            Suffix::Bellow => "bellow",
            Suffix::Belly => "belly",
            Suffix::Berry => "berry",
            Suffix::Billow => "billow",
            Suffix::Bird => "bird",
            Suffix::Bite => "bite",
            Suffix::Blaze => "blaze",
            Suffix::Blink => "blink",
            Suffix::Bloom => "bloom",
            Suffix::Blossom => "blossom",
            Suffix::Blotch => "blotch",
            Suffix::Blur => "blur",
            Suffix::Bone => "bone",
            Suffix::Bounce => "bounce",
            Suffix::Bracken => "bracken",
            Suffix::Bramble => "bramble",
            Suffix::Branch => "branch",
            Suffix::Break => "break",
            Suffix::Breeze => "breeze",
            Suffix::Briar => "briar",
            Suffix::Bright => "bright",
            Suffix::Brook => "brook",
            Suffix::Bubble => "bubble",
            Suffix::Bud => "bud",
            Suffix::Bumble => "bumble",
            Suffix::Burn => "burn",
            Suffix::Burr => "burr",
            Suffix::Burst => "burst",
            Suffix::Bush => "bush",
            Suffix::Buzz => "buzz",
            Suffix::Call => "call",
            Suffix::Catcher => "catcher",
            Suffix::Chase => "chase",
            Suffix::Chaser => "chaser",
            Suffix::Chasm => "chasm",
            Suffix::Chest => "chest",
            Suffix::Chill => "chill",
            Suffix::Chirp => "chirp",
            Suffix::Chomp => "chomp",
            Suffix::Cinder => "cinder",
            Suffix::Clash => "clash",
            Suffix::Cloud => "cloud",
            Suffix::Clover => "clover",
            Suffix::Crackle => "crackle",
            Suffix::Crash => "crash",
            Suffix::Crawl => "crawl",
            Suffix::Creek => "creek",
            Suffix::Crest => "crest",
            Suffix::Cry => "cry",
            Suffix::Curl => "curl",
            Suffix::Current => "current",
            Suffix::Daisy => "daisy",
            Suffix::Dance => "dance",
            Suffix::Dapple => "dapple",
            Suffix::Dart => "dart",
            Suffix::Dash => "dash",
            Suffix::Dawn => "dawn",
            Suffix::Daze => "daze",
            Suffix::Dazzle => "dazzle",
            Suffix::Dew => "dew",
            Suffix::Dream => "dream",
            Suffix::Drift => "drift",
            Suffix::Drizzle => "drizzle",
            Suffix::Drop => "drop",
            Suffix::Dusk => "dusk",
            Suffix::Dust => "dust",
            Suffix::Eagle => "eagle",
            Suffix::Ear => "ear",
            Suffix::Ears => "ears",
            Suffix::Echo => "echo",
            Suffix::Egg => "egg",
            Suffix::Ember => "ember",
            Suffix::Eye => "eye",
            Suffix::Eyes => "eyes",
            Suffix::Face => "face",
            Suffix::Falcon => "falcon",
            Suffix::Fall => "fall",
            Suffix::Fang => "fang",
            Suffix::Feather => "feather",
            Suffix::Fern => "fern",
            Suffix::Fin => "fin",
            Suffix::Fire => "fire",
            Suffix::Fish => "fish",
            Suffix::Flake => "flake",
            Suffix::Flame => "flame",
            Suffix::Flare => "flare",
            Suffix::Flash => "flash",
            Suffix::Fleck => "fleck",
            Suffix::Flick => "flick",
            Suffix::Flicker => "flicker",
            Suffix::Flight => "flight",
            Suffix::Flip => "flip",
            Suffix::Flit => "flit",
            Suffix::Flood => "flood",
            Suffix::Flow => "flow",
            Suffix::Flower => "flower",
            Suffix::Fluff => "fluff",
            Suffix::Fog => "fog",
            Suffix::Fox => "fox",
            Suffix::Freeze => "freeze",
            Suffix::Frost => "frost",
            Suffix::Fruit => "fruit",
            Suffix::Fuzz => "fuzz",
            Suffix::Gale => "gale",
            Suffix::Gaze => "gaze",
            Suffix::Ghost => "ghost",
            Suffix::Glare => "glare",
            Suffix::Gleam => "gleam",
            Suffix::Glide => "glide",
            Suffix::Glint => "glint",
            Suffix::Goose => "goose",
            Suffix::Gorse => "gorse",
            Suffix::Grass => "grass",
            Suffix::Growl => "growl",
            Suffix::Hail => "hail",
            Suffix::Hare => "hare",
            Suffix::Haven => "haven",
            Suffix::Hawk => "hawk",
            Suffix::Haze => "haze",
            Suffix::Heather => "heather",
            Suffix::Hiss => "hiss",
            Suffix::Hollow => "hollow",
            Suffix::Holly => "holly",
            Suffix::Honey => "honey",
            Suffix::Hope => "hope",
            Suffix::Howl => "howl",
            Suffix::Husk => "husk",
            Suffix::Ice => "ice",
            Suffix::Iris => "iris",
            Suffix::Ivy => "ivy",
            Suffix::Jaw => "jaw",
            Suffix::Jay => "jay",
            Suffix::Joy => "joy",
            Suffix::Jumble => "jumble",
            Suffix::Jump => "jump",
            Suffix::Kestrel => "kestrel",
            Suffix::Kick => "kick",
            Suffix::Kite => "kite",
            Suffix::Knoll => "knoll",
            Suffix::Lake => "lake",
            Suffix::Larch => "larch",
            Suffix::Laurel => "laurel",
            Suffix::Leaf => "leaf",
            Suffix::Leap => "leap",
            Suffix::Leg => "leg",
            Suffix::Leopard => "leopard",
            Suffix::Light => "light",
            Suffix::Lightning => "lightning",
            Suffix::Lilac => "lilac",
            Suffix::Lily => "lily",
            Suffix::Lion => "lion",
            Suffix::Lotus => "lotus",
            Suffix::Mallow => "mallow",
            Suffix::Mane => "mane",
            Suffix::Mark => "mark",
            Suffix::Mask => "mask",
            Suffix::Meadow => "meadow",
            Suffix::Mimic => "mimic",
            Suffix::Minnow => "minnow",
            Suffix::Mist => "mist",
            Suffix::Moon => "moon",
            Suffix::Moor => "moor",
            Suffix::Moss => "moss",
            Suffix::Moth => "moth",
            Suffix::Mouse => "mouse",
            Suffix::Munch => "munch",
            Suffix::Murk => "murk",
            Suffix::Muzzle => "muzzle",
            Suffix::Needle => "needle",
            Suffix::Nest => "nest",
            Suffix::Nettle => "nettle",
            Suffix::Newt => "newt",
            Suffix::Nibble => "nibble",
            Suffix::Night => "night",
            Suffix::Nip => "nip",
            Suffix::Noise => "noise",
            Suffix::Nose => "nose",
            Suffix::Nudge => "nudge",
            Suffix::Nut => "nut",
            Suffix::Pad => "pad",
            Suffix::Patch => "patch",
            Suffix::Path => "path",
            Suffix::Peak => "peak",
            Suffix::Petal => "petal",
            Suffix::Plume => "plume",
            Suffix::Pond => "pond",
            Suffix::Pool => "pool",
            Suffix::Poppy => "poppy",
            Suffix::Pounce => "pounce",
            Suffix::Prance => "prance",
            Suffix::Prickle => "prickle",
            Suffix::Puddle => "puddle",
            Suffix::Purr => "purr",
            Suffix::Quill => "quill",
            Suffix::Quiver => "quiver",
            Suffix::Rain => "rain",
            Suffix::Rapid => "rapid",
            Suffix::Raven => "raven",
            Suffix::Reed => "reed",
            Suffix::Rip => "rip",
            Suffix::Ripple => "ripple",
            Suffix::Rise => "rise",
            Suffix::River => "river",
            Suffix::Roach => "roach",
            Suffix::Roar => "roar",
            Suffix::Rock => "rock",
            Suffix::Root => "root",
            Suffix::Rose => "rose",
            Suffix::Rumble => "rumble",
            Suffix::Rump => "rump",
            Suffix::Run => "run",
            Suffix::Runner => "runner",
            Suffix::Rush => "rush",
            Suffix::Rustle => "rustle",
            Suffix::Scar => "scar",
            Suffix::Scratch => "scratch",
            Suffix::Screech => "screech",
            Suffix::Seed => "seed",
            Suffix::Seeker => "seeker",
            Suffix::Shade => "shade",
            Suffix::Shadow => "shadow",
            Suffix::Shard => "shard",
            Suffix::Shell => "shell",
            Suffix::Shimmer => "shimmer",
            Suffix::Shine => "shine",
            Suffix::Shiver => "shiver",
            Suffix::Shock => "shock",
            Suffix::Shriek => "shriek",
            Suffix::Sight => "sight",
            Suffix::Silk => "silk",
            Suffix::Skip => "skip",
            Suffix::Skitter => "skitter",
            Suffix::Sky => "sky",
            Suffix::Slash => "slash",
            Suffix::Slip => "slip",
            Suffix::Snap => "snap",
            Suffix::Snarl => "snarl",
            Suffix::Snout => "snout",
            Suffix::Snow => "snow",
            Suffix::Soar => "soar",
            Suffix::Song => "song",
            Suffix::Spark => "spark",
            Suffix::Speck => "speck",
            Suffix::Speckle => "speckle",
            Suffix::Spider => "spider",
            Suffix::Spike => "spike",
            Suffix::Spirit => "spirit",
            Suffix::Splash => "splash",
            Suffix::Splinter => "splinter",
            Suffix::Spore => "spore",
            Suffix::Spot => "spot",
            Suffix::Spots => "spots",
            Suffix::Spring => "spring",
            Suffix::Sprout => "sprout",
            Suffix::Stalk => "stalk",
            Suffix::Stem => "stem",
            Suffix::Step => "step",
            Suffix::Sting => "sting",
            Suffix::Stone => "stone",
            Suffix::Storm => "storm",
            Suffix::Streak => "streak",
            Suffix::Stream => "stream",
            Suffix::Strike => "strike",
            Suffix::Stripe => "stripe",
            Suffix::Sun => "sun",
            Suffix::Swarm => "swarm",
            Suffix::Swipe => "swipe",
            Suffix::Swoop => "swoop",
            Suffix::Talon => "talon",
            Suffix::Tangle => "tangle",
            Suffix::Thistle => "thistle",
            Suffix::Thorn => "thorn",
            Suffix::Thrift => "thrift",
            Suffix::Throat => "throat",
            Suffix::Thrush => "thrush",
            Suffix::Thud => "thud",
            Suffix::Thunder => "thunder",
            Suffix::Tiger => "tiger",
            Suffix::Timber => "timber",
            Suffix::Toe => "toe",
            Suffix::Tooth => "tooth",
            Suffix::Trail => "trail",
            Suffix::Tree => "tree",
            Suffix::Trot => "trot",
            Suffix::Tumble => "tumble",
            Suffix::Twist => "twist",
            Suffix::Valley => "valley",
            Suffix::Watcher => "watcher",
            Suffix::Water => "water",
            Suffix::Wave => "wave",
            Suffix::Web => "web",
            Suffix::Whisper => "whisper",
            Suffix::Whistle => "whistle",
            Suffix::Willow => "willow",
            Suffix::Wind => "wind",
            Suffix::Wing => "wing",
            Suffix::Wish => "wish",
            Suffix::Wisp => "wisp",
            Suffix::Zoom => "zoom",
        };
        write!(f, "{}", suffix_str)
    }
}



#[derive(Debug, Copy, Clone, Component)]
pub enum Prefix {
    Adder, Alder, Ant, Antler, Aphid, Apple, Apricot, Arch, Aspen, Aster, 
    Badger, Barley, Basil, Bass, Bay, Beam, Bear, Beaver, Bee, Beech, 
    Beetle, Berry, Big, Billow, Birch, Bird, Bite, Bitter, Bittern, Bliss, 
    Blizzard, Bloom, Blossom, Blotch, Bluebell, Bluff, Bog, Borage, Bough, 
    Boulder, Bounce, Bracken, Bramble, Brave, Breeze, Briar, Bright, Brindle, 
    Bristle, Broken, Brook, Brush, Bubbling, Bud, Bug, Bumble, Burdock, Burr, 
    Burrow, Bush, Butterfly, Buzzard, Carnation, Carp, Caterpillar, Cave, Cedar, 
    Chaffinch, Chasing, Cherry, Chervil, Chestnut, Chirp, Chive, Cicada, Claw, 
    Clay, Clear, Cliff, Clover, Comfrey, Condor, Cone, Conifer, Conker, Copse, 
    Cougar, Coyote, Crag, Crane, Creek, Cress, Crest, Crested, Cricket, Crooked, 
    Crouch, Curl, Curlew, Curly, Current, Cypress, Dahlia, Daisy, Dancing, Dapple, 
    Dappled, Dart, Dash, Dawn, Dazzle, Dew, Dog, Down, Downy, Dream, Drift, Drizzle, 
    Droplet, Dry, Duck, Dusk, Eagle, Echo, Edelweiss, Egret, Elder, Elm, Ermine, 
    Faith, Falcon, Fallen, Falling, Fallow, Fawn, Feather, Fennel, Fern, Ferret, 
    Fickle, Fidget, Fierce, Fin, Finch, Fir, Fish, Flail, Flash, Flax, Fleck, 
    Fleet, Flicker, Flight, Flint, Flip, Flit, Flood, Flower, Fluff, Fluffy, 
    Flutter, Fly, Fog, Foggy, Freckle, Fringe, Frog, Frond, Fruit, Fumble, 
    Furled, Furze, Fuzz, Fuzzy, Gale, Gander, Gardenia, Garlic, Gentle, Gill, 
    Glade, Goose, Gorge, Gorse, Grass, Gravel, Grouse, Gull, Guppy, Gust, Hail, 
    Half, Hare, Hatch, Haven, Hawk, Hay, Hazel, Hazy, Heart, Heath, Heavy, 
    Hemlock, Heron, Hill, Hollow, Holly, Honey, Hoot, Hop, Hope, Hornet, Hound, 
    Howl, Hush, Hyacinth, Iris, Ivy, Jackdaw, Jagged, Jay, Jumble, Jump, Junco, 
    Juniper, Kestrel, Kink, Kite, Lake, Larch, Lark, Laurel, Lavender, Leaf, 
    Leap, Leopard, Lichen, Light, Lightning, Lilac, Lily, Lion, Little, Lizard, 
    Locust, Long, Lotus, Loud, Low, Luck, Lupine, Lynx, Mallow, Mantis, Maple, 
    Marigold, Marsh, Meadow, Midge, Milk, Milkweed, Mink, Minnow, Mistle, Mite, 
    Mole, Moon, Moor, Morning, Moss, Mossy, Moth, Mottle, Mottled, Mouse, Mumble, 
    Murk, Myrtle, Nectar, Needle, Nettle, Newt, Nightingale, Nimble, Nut, Oak, 
    Oat, Odd, One, Oriole, Osprey, Pansy, Panther, Parsley, Partridge, Patch, 
    Patchouli, Peak, Pear, Peat, Perch, Petal, Petunia, Pheasant, Pigeon, Pike, 
    Pine, Piper, Plover, Plum, Pod, Pond, Pool, Pop, Poppy, Posy, Pounce, Prance, 
    Prickle, Prim, Primrose, Puddle, Python, Quail, Quick, Quiet, Quill, Quiver, 
    Rabbit, Raccoon, Ragged, Rain, Rainbow, Rat, Rattle, Raven, Reed, Ridge, Rift, 
    Rindle, Ripple, River, Roach, Roar, Rook, Root, Rose, Rosy, Rowan, Rubble, 
    Runnel, Running, Rush, Rye, Sable, Sapling, Scorch, Scratch, Seed, Serpent, 
    Shard, Sharp, Shell, Shimmer, Shine, Shining, Shivering, Short, Shrew, Shrub, 
    Shy, Silent, Silk, Silt, Skip, Sky, Slate, Sleek, Sleepy, Sleet, Slight, Slip, 
    Sloe, Slope, Slumber, Small, Snail, Snake, Snap, Sneeze, Snip, Snowy, Soft, 
    Song, Sorrel, Spark, Sparrow, Speckle, Spider, Spike, Splash, Splinter, Spore, 
    Spot, Spotted, Spring, Sprout, Spruce, Squirrel, Starling, Stem, Stoat, Stork, 
    Streak, Stream, Strike, Stumpy, Sunny, Swallow, Swamp, Swarm, Sweet, Swift, 
    Sycamore, Tadpole, Tall, Talon, Tangle, Tansy, Tawny, Tempest, Thistle, Thorn, 
    Thrift, Thrush, Thunder, Thyme, Tiger, Timber, Tiny, Toad, Torn, Tremble, 
    Trickle, Trout, Tuft, Tulip, Tumble, Turtle, Valley, Vine, Vixen, Wasp, 
    Weasel, Web, Weed, Weevil, Wet, Wheat, Whimsy, Whirl, Whisker, Whisper, 
    Whispering, Whistle, Whorl, Wild, Willow, Wind, Wing, Wish, Wisteria, Wolf, 
    Wolverine, Wood, Worm, Wren, Yarrow, Yew, Zinnia,
}

pub const PREFIXES: &[Prefix] = &[
    Prefix::Adder, Prefix::Alder, Prefix::Ant, Prefix::Antler, Prefix::Aphid, Prefix::Apple, Prefix::Apricot, 
    Prefix::Arch, Prefix::Aspen, Prefix::Aster, Prefix::Badger, Prefix::Barley, Prefix::Basil, Prefix::Bass, 
    Prefix::Bay, Prefix::Beam, Prefix::Bear, Prefix::Beaver, Prefix::Bee, Prefix::Beech, Prefix::Beetle, 
    Prefix::Berry, Prefix::Big, Prefix::Billow, Prefix::Birch, Prefix::Bird, Prefix::Bite, Prefix::Bitter, 
    Prefix::Bittern, Prefix::Bliss, Prefix::Blizzard, Prefix::Bloom, Prefix::Blossom, Prefix::Blotch, 
    Prefix::Bluebell, Prefix::Bluff, Prefix::Bog, Prefix::Borage, Prefix::Bough, Prefix::Boulder, Prefix::Bounce, 
    Prefix::Bracken, Prefix::Bramble, Prefix::Brave, Prefix::Breeze, Prefix::Briar, Prefix::Bright, Prefix::Brindle, 
    Prefix::Bristle, Prefix::Broken, Prefix::Brook, Prefix::Brush, Prefix::Bubbling, Prefix::Bud, Prefix::Bug, 
    Prefix::Bumble, Prefix::Burdock, Prefix::Burr, Prefix::Burrow, Prefix::Bush, Prefix::Butterfly, Prefix::Buzzard, 
    Prefix::Carnation, Prefix::Carp, Prefix::Caterpillar, Prefix::Cave, Prefix::Cedar, Prefix::Chaffinch, 
    Prefix::Chasing, Prefix::Cherry, Prefix::Chervil, Prefix::Chestnut, Prefix::Chirp, Prefix::Chive, Prefix::Cicada, 
    Prefix::Claw, Prefix::Clay, Prefix::Clear, Prefix::Cliff, Prefix::Clover, Prefix::Comfrey, Prefix::Condor, 
    Prefix::Cone, Prefix::Conifer, Prefix::Conker, Prefix::Copse, Prefix::Cougar, Prefix::Coyote, Prefix::Crag, 
    Prefix::Crane, Prefix::Creek, Prefix::Cress, Prefix::Crest, Prefix::Crested, Prefix::Cricket, Prefix::Crooked, 
    Prefix::Crouch, Prefix::Curl, Prefix::Curlew, Prefix::Curly, Prefix::Current, Prefix::Cypress, Prefix::Dahlia, 
    Prefix::Daisy, Prefix::Dancing, Prefix::Dapple, Prefix::Dappled, Prefix::Dart, Prefix::Dash, Prefix::Dawn, 
    Prefix::Dazzle, Prefix::Dew, Prefix::Dog, Prefix::Down, Prefix::Downy, Prefix::Dream, Prefix::Drift, Prefix::Drizzle, 
    Prefix::Droplet, Prefix::Dry, Prefix::Duck, Prefix::Dusk, Prefix::Eagle, Prefix::Echo, Prefix::Edelweiss, 
    Prefix::Egret, Prefix::Elder, Prefix::Elm, Prefix::Ermine, Prefix::Faith, Prefix::Falcon, Prefix::Fallen, 
    Prefix::Falling, Prefix::Fallow, Prefix::Fawn, Prefix::Feather, Prefix::Fennel, Prefix::Fern, Prefix::Ferret, 
    Prefix::Fickle, Prefix::Fidget, Prefix::Fierce, Prefix::Fin, Prefix::Finch, Prefix::Fir, Prefix::Fish, Prefix::Flail, 
    Prefix::Flash, Prefix::Flax, Prefix::Fleck, Prefix::Fleet, Prefix::Flicker, Prefix::Flight, Prefix::Flint, Prefix::Flip, 
    Prefix::Flit, Prefix::Flood, Prefix::Flower, Prefix::Fluff, Prefix::Fluffy, Prefix::Flutter, Prefix::Fly, Prefix::Fog, 
    Prefix::Foggy, Prefix::Freckle, Prefix::Fringe, Prefix::Frog, Prefix::Frond, Prefix::Fruit, Prefix::Fumble, Prefix::Furled, 
    Prefix::Furze, Prefix::Fuzz, Prefix::Fuzzy, Prefix::Gale, Prefix::Gander, Prefix::Gardenia, Prefix::Garlic, Prefix::Gentle, 
    Prefix::Gill, Prefix::Glade, Prefix::Goose, Prefix::Gorge, Prefix::Gorse, Prefix::Grass, Prefix::Gravel, Prefix::Grouse, 
    Prefix::Gull, Prefix::Guppy, Prefix::Gust, Prefix::Hail, Prefix::Half, Prefix::Hare, Prefix::Hatch, Prefix::Haven, 
    Prefix::Hawk, Prefix::Hay, Prefix::Hazel, Prefix::Hazy, Prefix::Heart, Prefix::Heath, Prefix::Heavy, Prefix::Hemlock, 
    Prefix::Heron, Prefix::Hill, Prefix::Hollow, Prefix::Holly, Prefix::Honey, Prefix::Hoot, Prefix::Hop, Prefix::Hope, 
    Prefix::Hornet, Prefix::Hound, Prefix::Howl, Prefix::Hush, Prefix::Hyacinth, Prefix::Iris, Prefix::Ivy, Prefix::Jackdaw, 
    Prefix::Jagged, Prefix::Jay, Prefix::Jumble, Prefix::Jump, Prefix::Junco, Prefix::Juniper, Prefix::Kestrel, Prefix::Kink, 
    Prefix::Kite, Prefix::Lake, Prefix::Larch, Prefix::Lark, Prefix::Laurel, Prefix::Lavender, Prefix::Leaf, Prefix::Leap, 
    Prefix::Leopard, Prefix::Lichen, Prefix::Light, Prefix::Lightning, Prefix::Lilac, Prefix::Lily, Prefix::Lion, Prefix::Little, 
    Prefix::Lizard, Prefix::Locust, Prefix::Long, Prefix::Lotus, Prefix::Loud, Prefix::Low, Prefix::Luck, Prefix::Lupine, 
    Prefix::Lynx, Prefix::Mallow, Prefix::Mantis, Prefix::Maple, Prefix::Marigold, Prefix::Marsh, Prefix::Meadow, Prefix::Midge, 
    Prefix::Milk, Prefix::Milkweed, Prefix::Mink, Prefix::Minnow, Prefix::Mistle, Prefix::Mite, Prefix::Mole, Prefix::Moon, 
    Prefix::Moor, Prefix::Morning, Prefix::Moss, Prefix::Mossy, Prefix::Moth, Prefix::Mottle, Prefix::Mottled, Prefix::Mouse, 
    Prefix::Mumble, Prefix::Murk, Prefix::Myrtle, Prefix::Nectar, Prefix::Needle, Prefix::Nettle, Prefix::Newt, Prefix::Nightingale, 
    Prefix::Nimble, Prefix::Nut, Prefix::Oak, Prefix::Oat, Prefix::Odd, Prefix::One, Prefix::Oriole, Prefix::Osprey, Prefix::Pansy, 
    Prefix::Panther, Prefix::Parsley, Prefix::Partridge, Prefix::Patch, Prefix::Patchouli, Prefix::Peak, Prefix::Pear, Prefix::Peat, 
    Prefix::Perch, Prefix::Petal, Prefix::Petunia, Prefix::Pheasant, Prefix::Pigeon, Prefix::Pike, Prefix::Pine, Prefix::Piper, 
    Prefix::Plover, Prefix::Plum, Prefix::Pod, Prefix::Pond, Prefix::Pool, Prefix::Pop, Prefix::Poppy, Prefix::Posy, Prefix::Pounce, 
    Prefix::Prance, Prefix::Prickle, Prefix::Prim, Prefix::Primrose, Prefix::Puddle, Prefix::Python, Prefix::Quail, Prefix::Quick, 
    Prefix::Quiet, Prefix::Quill, Prefix::Quiver, Prefix::Rabbit, Prefix::Raccoon, Prefix::Ragged, Prefix::Rain, Prefix::Rainbow, 
    Prefix::Rat, Prefix::Rattle, Prefix::Raven, Prefix::Reed, Prefix::Ridge, Prefix::Rift, Prefix::Rindle, Prefix::Ripple, Prefix::River, 
    Prefix::Roach, Prefix::Roar, Prefix::Rook, Prefix::Root, Prefix::Rose, Prefix::Rosy, Prefix::Rowan, Prefix::Rubble, Prefix::Runnel, 
    Prefix::Running, Prefix::Rush, Prefix::Rye, Prefix::Sable, Prefix::Sapling, Prefix::Scorch, Prefix::Scratch, Prefix::Seed, 
    Prefix::Serpent, Prefix::Shard, Prefix::Sharp, Prefix::Shell, Prefix::Shimmer, Prefix::Shine, Prefix::Shining, Prefix::Shivering, 
    Prefix::Short, Prefix::Shrew, Prefix::Shrub, Prefix::Shy, Prefix::Silent, Prefix::Silk, Prefix::Silt, Prefix::Skip, Prefix::Sky, 
    Prefix::Slate, Prefix::Sleek, Prefix::Sleepy, Prefix::Sleet, Prefix::Slight, Prefix::Slip, Prefix::Sloe, Prefix::Slope, 
    Prefix::Slumber, Prefix::Small, Prefix::Snail, Prefix::Snake, Prefix::Snap, Prefix::Sneeze, Prefix::Snip, Prefix::Snowy, 
    Prefix::Soft, Prefix::Song, Prefix::Sorrel, Prefix::Spark, Prefix::Sparrow, Prefix::Speckle, Prefix::Spider, Prefix::Spike, 
    Prefix::Splash, Prefix::Splinter, Prefix::Spore, Prefix::Spot, Prefix::Spotted, Prefix::Spring, Prefix::Sprout, Prefix::Spruce, 
    Prefix::Squirrel, Prefix::Starling, Prefix::Stem, Prefix::Stoat, Prefix::Stork, Prefix::Streak, Prefix::Stream, Prefix::Strike, 
    Prefix::Stumpy, Prefix::Sunny, Prefix::Swallow, Prefix::Swamp, Prefix::Swarm, Prefix::Sweet, Prefix::Swift, Prefix::Sycamore, 
    Prefix::Tadpole, Prefix::Tall, Prefix::Talon, Prefix::Tangle, Prefix::Tansy, Prefix::Tawny, Prefix::Tempest, Prefix::Thistle, 
    Prefix::Thorn, Prefix::Thrift, Prefix::Thrush, Prefix::Thunder, Prefix::Thyme, Prefix::Tiger, Prefix::Timber, Prefix::Tiny, 
    Prefix::Toad, Prefix::Torn, Prefix::Tremble, Prefix::Trickle, Prefix::Trout, Prefix::Tuft, Prefix::Tulip, Prefix::Tumble, 
    Prefix::Turtle, Prefix::Valley, Prefix::Vine, Prefix::Vixen, Prefix::Wasp, Prefix::Weasel, Prefix::Web, Prefix::Weed, Prefix::Weevil, 
    Prefix::Wet, Prefix::Wheat, Prefix::Whimsy, Prefix::Whirl, Prefix::Whisker, Prefix::Whisper, Prefix::Whispering, Prefix::Whistle, 
    Prefix::Whorl, Prefix::Wild, Prefix::Willow, Prefix::Wind, Prefix::Wing, Prefix::Wish, Prefix::Wisteria, Prefix::Wolf, Prefix::Wolverine, 
    Prefix::Wood, Prefix::Worm, Prefix::Wren, Prefix::Yarrow, Prefix::Yew, Prefix::Zinnia,
];

impl fmt::Display for Prefix {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let prefix_str = match self {
            Prefix::Adder => "Adder",
            Prefix::Alder => "Alder",
            Prefix::Ant => "Ant",
            Prefix::Antler => "Antler",
            Prefix::Aphid => "Aphid",
            Prefix::Apple => "Apple",
            Prefix::Apricot => "Apricot",
            Prefix::Arch => "Arch",
            Prefix::Aspen => "Aspen",
            Prefix::Aster => "Aster",
            Prefix::Badger => "Badger",
            Prefix::Barley => "Barley",
            Prefix::Basil => "Basil",
            Prefix::Bass => "Bass",
            Prefix::Bay => "Bay",
            Prefix::Beam => "Beam",
            Prefix::Bear => "Bear",
            Prefix::Beaver => "Beaver",
            Prefix::Bee => "Bee",
            Prefix::Beech => "Beech",
            Prefix::Beetle => "Beetle",
            Prefix::Berry => "Berry",
            Prefix::Big => "Big",
            Prefix::Billow => "Billow",
            Prefix::Birch => "Birch",
            Prefix::Bird => "Bird",
            Prefix::Bite => "Bite",
            Prefix::Bitter => "Bitter",
            Prefix::Bittern => "Bittern",
            Prefix::Bliss => "Bliss",
            Prefix::Blizzard => "Blizzard",
            Prefix::Bloom => "Bloom",
            Prefix::Blossom => "Blossom",
            Prefix::Blotch => "Blotch",
            Prefix::Bluebell => "Bluebell",
            Prefix::Bluff => "Bluff",
            Prefix::Bog => "Bog",
            Prefix::Borage => "Borage",
            Prefix::Bough => "Bough",
            Prefix::Boulder => "Boulder",
            Prefix::Bounce => "Bounce",
            Prefix::Bracken => "Bracken",
            Prefix::Bramble => "Bramble",
            Prefix::Brave => "Brave",
            Prefix::Breeze => "Breeze",
            Prefix::Briar => "Briar",
            Prefix::Bright => "Bright",
            Prefix::Brindle => "Brindle",
            Prefix::Bristle => "Bristle",
            Prefix::Broken => "Broken",
            Prefix::Brook => "Brook",
            Prefix::Brush => "Brush",
            Prefix::Bubbling => "Bubbling",
            Prefix::Bud => "Bud",
            Prefix::Bug => "Bug",
            Prefix::Bumble => "Bumble",
            Prefix::Burdock => "Burdock",
            Prefix::Burr => "Burr",
            Prefix::Burrow => "Burrow",
            Prefix::Bush => "Bush",
            Prefix::Butterfly => "Butterfly",
            Prefix::Buzzard => "Buzzard",
            Prefix::Carnation => "Carnation",
            Prefix::Carp => "Carp",
            Prefix::Caterpillar => "Caterpillar",
            Prefix::Cave => "Cave",
            Prefix::Cedar => "Cedar",
            Prefix::Chaffinch => "Chaffinch",
            Prefix::Chasing => "Chasing",
            Prefix::Cherry => "Cherry",
            Prefix::Chervil => "Chervil",
            Prefix::Chestnut => "Chestnut",
            Prefix::Chirp => "Chirp",
            Prefix::Chive => "Chive",
            Prefix::Cicada => "Cicada",
            Prefix::Claw => "Claw",
            Prefix::Clay => "Clay",
            Prefix::Clear => "Clear",
            Prefix::Cliff => "Cliff",
            Prefix::Clover => "Clover",
            Prefix::Comfrey => "Comfrey",
            Prefix::Condor => "Condor",
            Prefix::Cone => "Cone",
            Prefix::Conifer => "Conifer",
            Prefix::Conker => "Conker",
            Prefix::Copse => "Copse",
            Prefix::Cougar => "Cougar",
            Prefix::Coyote => "Coyote",
            Prefix::Crag => "Crag",
            Prefix::Crane => "Crane",
            Prefix::Creek => "Creek",
            Prefix::Cress => "Cress",
            Prefix::Crest => "Crest",
            Prefix::Crested => "Crested",
            Prefix::Cricket => "Cricket",
            Prefix::Crooked => "Crooked",
            Prefix::Crouch => "Crouch",
            Prefix::Curl => "Curl",
            Prefix::Curlew => "Curlew",
            Prefix::Curly => "Curly",
            Prefix::Current => "Current",
            Prefix::Cypress => "Cypress",
            Prefix::Dahlia => "Dahlia",
            Prefix::Daisy => "Daisy",
            Prefix::Dancing => "Dancing",
            Prefix::Dapple => "Dapple",
            Prefix::Dappled => "Dappled",
            Prefix::Dart => "Dart",
            Prefix::Dash => "Dash",
            Prefix::Dawn => "Dawn",
            Prefix::Dazzle => "Dazzle",
            Prefix::Dew => "Dew",
            Prefix::Dog => "Dog",
            Prefix::Down => "Down",
            Prefix::Downy => "Downy",
            Prefix::Dream => "Dream",
            Prefix::Drift => "Drift",
            Prefix::Drizzle => "Drizzle",
            Prefix::Droplet => "Droplet",
            Prefix::Dry => "Dry",
            Prefix::Duck => "Duck",
            Prefix::Dusk => "Dusk",
            Prefix::Eagle => "Eagle",
            Prefix::Echo => "Echo",
            Prefix::Edelweiss => "Edelweiss",
            Prefix::Egret => "Egret",
            Prefix::Elder => "Elder",
            Prefix::Elm => "Elm",
            Prefix::Ermine => "Ermine",
            Prefix::Faith => "Faith",
            Prefix::Falcon => "Falcon",
            Prefix::Fallen => "Fallen",
            Prefix::Falling => "Falling",
            Prefix::Fallow => "Fallow",
            Prefix::Fawn => "Fawn",
            Prefix::Feather => "Feather",
            Prefix::Fennel => "Fennel",
            Prefix::Fern => "Fern",
            Prefix::Ferret => "Ferret",
            Prefix::Fickle => "Fickle",
            Prefix::Fidget => "Fidget",
            Prefix::Fierce => "Fierce",
            Prefix::Fin => "Fin",
            Prefix::Finch => "Finch",
            Prefix::Fir => "Fir",
            Prefix::Fish => "Fish",
            Prefix::Flail => "Flail",
            Prefix::Flash => "Flash",
            Prefix::Flax => "Flax",
            Prefix::Fleck => "Fleck",
            Prefix::Fleet => "Fleet",
            Prefix::Flicker => "Flicker",
            Prefix::Flight => "Flight",
            Prefix::Flint => "Flint",
            Prefix::Flip => "Flip",
            Prefix::Flit => "Flit",
            Prefix::Flood => "Flood",
            Prefix::Flower => "Flower",
            Prefix::Fluff => "Fluff",
            Prefix::Fluffy => "Fluffy",
            Prefix::Flutter => "Flutter",
            Prefix::Fly => "Fly",
            Prefix::Fog => "Fog",
            Prefix::Foggy => "Foggy",
            Prefix::Freckle => "Freckle",
            Prefix::Fringe => "Fringe",
            Prefix::Frog => "Frog",
            Prefix::Frond => "Frond",
            Prefix::Fruit => "Fruit",
            Prefix::Fumble => "Fumble",
            Prefix::Furled => "Furled",
            Prefix::Furze => "Furze",
            Prefix::Fuzz => "Fuzz",
            Prefix::Fuzzy => "Fuzzy",
            Prefix::Gale => "Gale",
            Prefix::Gander => "Gander",
            Prefix::Gardenia => "Gardenia",
            Prefix::Garlic => "Garlic",
            Prefix::Gentle => "Gentle",
            Prefix::Gill => "Gill",
            Prefix::Glade => "Glade",
            Prefix::Goose => "Goose",
            Prefix::Gorge => "Gorge",
            Prefix::Gorse => "Gorse",
            Prefix::Grass => "Grass",
            Prefix::Gravel => "Gravel",
            Prefix::Grouse => "Grouse",
            Prefix::Gull => "Gull",
            Prefix::Guppy => "Guppy",
            Prefix::Gust => "Gust",
            Prefix::Hail => "Hail",
            Prefix::Half => "Half",
            Prefix::Hare => "Hare",
            Prefix::Hatch => "Hatch",
            Prefix::Haven => "Haven",
            Prefix::Hawk => "Hawk",
            Prefix::Hay => "Hay",
            Prefix::Hazel => "Hazel",
            Prefix::Hazy => "Hazy",
            Prefix::Heart => "Heart",
            Prefix::Heath => "Heath",
            Prefix::Heavy => "Heavy",
            Prefix::Hemlock => "Hemlock",
            Prefix::Heron => "Heron",
            Prefix::Hill => "Hill",
            Prefix::Hollow => "Hollow",
            Prefix::Holly => "Holly",
            Prefix::Honey => "Honey",
            Prefix::Hoot => "Hoot",
            Prefix::Hop => "Hop",
            Prefix::Hope => "Hope",
            Prefix::Hornet => "Hornet",
            Prefix::Hound => "Hound",
            Prefix::Howl => "Howl",
            Prefix::Hush => "Hush",
            Prefix::Hyacinth => "Hyacinth",
            Prefix::Iris => "Iris",
            Prefix::Ivy => "Ivy",
            Prefix::Jackdaw => "Jackdaw",
            Prefix::Jagged => "Jagged",
            Prefix::Jay => "Jay",
            Prefix::Jumble => "Jumble",
            Prefix::Jump => "Jump",
            Prefix::Junco => "Junco",
            Prefix::Juniper => "Juniper",
            Prefix::Kestrel => "Kestrel",
            Prefix::Kink => "Kink",
            Prefix::Kite => "Kite",
            Prefix::Lake => "Lake",
            Prefix::Larch => "Larch",
            Prefix::Lark => "Lark",
            Prefix::Laurel => "Laurel",
            Prefix::Lavender => "Lavender",
            Prefix::Leaf => "Leaf",
            Prefix::Leap => "Leap",
            Prefix::Leopard => "Leopard",
            Prefix::Lichen => "Lichen",
            Prefix::Light => "Light",
            Prefix::Lightning => "Lightning",
            Prefix::Lilac => "Lilac",
            Prefix::Lily => "Lily",
            Prefix::Lion => "Lion",
            Prefix::Little => "Little",
            Prefix::Lizard => "Lizard",
            Prefix::Locust => "Locust",
            Prefix::Long => "Long",
            Prefix::Lotus => "Lotus",
            Prefix::Loud => "Loud",
            Prefix::Low => "Low",
            Prefix::Luck => "Luck",
            Prefix::Lupine => "Lupine",
            Prefix::Lynx => "Lynx",
            Prefix::Mallow => "Mallow",
            Prefix::Mantis => "Mantis",
            Prefix::Maple => "Maple",
            Prefix::Marigold => "Marigold",
            Prefix::Marsh => "Marsh",
            Prefix::Meadow => "Meadow",
            Prefix::Midge => "Midge",
            Prefix::Milk => "Milk",
            Prefix::Milkweed => "Milkweed",
            Prefix::Mink => "Mink",
            Prefix::Minnow => "Minnow",
            Prefix::Mistle => "Mistle",
            Prefix::Mite => "Mite",
            Prefix::Mole => "Mole",
            Prefix::Moon => "Moon",
            Prefix::Moor => "Moor",
            Prefix::Morning => "Morning",
            Prefix::Moss => "Moss",
            Prefix::Mossy => "Mossy",
            Prefix::Moth => "Moth",
            Prefix::Mottle => "Mottle",
            Prefix::Mottled => "Mottled",
            Prefix::Mouse => "Mouse",
            Prefix::Mumble => "Mumble",
            Prefix::Murk => "Murk",
            Prefix::Myrtle => "Myrtle",
            Prefix::Nectar => "Nectar",
            Prefix::Needle => "Needle",
            Prefix::Nettle => "Nettle",
            Prefix::Newt => "Newt",
            Prefix::Nightingale => "Nightingale",
            Prefix::Nimble => "Nimble",
            Prefix::Nut => "Nut",
            Prefix::Oak => "Oak",
            Prefix::Oat => "Oat",
            Prefix::Odd => "Odd",
            Prefix::One => "One",
            Prefix::Oriole => "Oriole",
            Prefix::Osprey => "Osprey",
            Prefix::Pansy => "Pansy",
            Prefix::Panther => "Panther",
            Prefix::Parsley => "Parsley",
            Prefix::Partridge => "Partridge",
            Prefix::Patch => "Patch",
            Prefix::Patchouli => "Patchouli",
            Prefix::Peak => "Peak",
            Prefix::Pear => "Pear",
            Prefix::Peat => "Peat",
            Prefix::Perch => "Perch",
            Prefix::Petal => "Petal",
            Prefix::Petunia => "Petunia",
            Prefix::Pheasant => "Pheasant",
            Prefix::Pigeon => "Pigeon",
            Prefix::Pike => "Pike",
            Prefix::Pine => "Pine",
            Prefix::Piper => "Piper",
            Prefix::Plover => "Plover",
            Prefix::Plum => "Plum",
            Prefix::Pod => "Pod",
            Prefix::Pond => "Pond",
            Prefix::Pool => "Pool",
            Prefix::Pop => "Pop",
            Prefix::Poppy => "Poppy",
            Prefix::Posy => "Posy",
            Prefix::Pounce => "Pounce",
            Prefix::Prance => "Prance",
            Prefix::Prickle => "Prickle",
            Prefix::Prim => "Prim",
            Prefix::Primrose => "Primrose",
            Prefix::Puddle => "Puddle",
            Prefix::Python => "Python",
            Prefix::Quail => "Quail",
            Prefix::Quick => "Quick",
            Prefix::Quiet => "Quiet",
            Prefix::Quill => "Quill",
            Prefix::Quiver => "Quiver",
            Prefix::Rabbit => "Rabbit",
            Prefix::Raccoon => "Raccoon",
            Prefix::Ragged => "Ragged",
            Prefix::Rain => "Rain",
            Prefix::Rainbow => "Rainbow",
            Prefix::Rat => "Rat",
            Prefix::Rattle => "Rattle",
            Prefix::Raven => "Raven",
            Prefix::Reed => "Reed",
            Prefix::Ridge => "Ridge",
            Prefix::Rift => "Rift",
            Prefix::Rindle => "Rindle",
            Prefix::Ripple => "Ripple",
            Prefix::River => "River",
            Prefix::Roach => "Roach",
            Prefix::Roar => "Roar",
            Prefix::Rook => "Rook",
            Prefix::Root => "Root",
            Prefix::Rose => "Rose",
            Prefix::Rosy => "Rosy",
            Prefix::Rowan => "Rowan",
            Prefix::Rubble => "Rubble",
            Prefix::Runnel => "Runnel",
            Prefix::Running => "Running",
            Prefix::Rush => "Rush",
            Prefix::Rye => "Rye",
            Prefix::Sable => "Sable",
            Prefix::Sapling => "Sapling",
            Prefix::Scorch => "Scorch",
            Prefix::Scratch => "Scratch",
            Prefix::Seed => "Seed",
            Prefix::Serpent => "Serpent",
            Prefix::Shard => "Shard",
            Prefix::Sharp => "Sharp",
            Prefix::Shell => "Shell",
            Prefix::Shimmer => "Shimmer",
            Prefix::Shine => "Shine",
            Prefix::Shining => "Shining",
            Prefix::Shivering => "Shivering",
            Prefix::Short => "Short",
            Prefix::Shrew => "Shrew",
            Prefix::Shrub => "Shrub",
            Prefix::Shy => "Shy",
            Prefix::Silent => "Silent",
            Prefix::Silk => "Silk",
            Prefix::Silt => "Silt",
            Prefix::Skip => "Skip",
            Prefix::Sky => "Sky",
            Prefix::Slate => "Slate",
            Prefix::Sleek => "Sleek",
            Prefix::Sleepy => "Sleepy",
            Prefix::Sleet => "Sleet",
            Prefix::Slight => "Slight",
            Prefix::Slip => "Slip",
            Prefix::Sloe => "Sloe",
            Prefix::Slope => "Slope",
            Prefix::Slumber => "Slumber",
            Prefix::Small => "Small",
            Prefix::Snail => "Snail",
            Prefix::Snake => "Snake",
            Prefix::Snap => "Snap",
            Prefix::Sneeze => "Sneeze",
            Prefix::Snip => "Snip",
            Prefix::Snowy => "Snowy",
            Prefix::Soft => "Soft",
            Prefix::Song => "Song",
            Prefix::Sorrel => "Sorrel",
            Prefix::Spark => "Spark",
            Prefix::Sparrow => "Sparrow",
            Prefix::Speckle => "Speckle",
            Prefix::Spider => "Spider",
            Prefix::Spike => "Spike",
            Prefix::Splash => "Splash",
            Prefix::Splinter => "Splinter",
            Prefix::Spore => "Spore",
            Prefix::Spot => "Spot",
            Prefix::Spotted => "Spotted",
            Prefix::Spring => "Spring",
            Prefix::Sprout => "Sprout",
            Prefix::Spruce => "Spruce",
            Prefix::Squirrel => "Squirrel",
            Prefix::Starling => "Starling",
            Prefix::Stem => "Stem",
            Prefix::Stoat => "Stoat",
            Prefix::Stork => "Stork",
            Prefix::Streak => "Streak",
            Prefix::Stream => "Stream",
            Prefix::Strike => "Strike",
            Prefix::Stumpy => "Stumpy",
            Prefix::Sunny => "Sunny",
            Prefix::Swallow => "Swallow",
            Prefix::Swamp => "Swamp",
            Prefix::Swarm => "Swarm",
            Prefix::Sweet => "Sweet",
            Prefix::Swift => "Swift",
            Prefix::Sycamore => "Sycamore",
            Prefix::Tadpole => "Tadpole",
            Prefix::Tall => "Tall",
            Prefix::Talon => "Talon",
            Prefix::Tangle => "Tangle",
            Prefix::Tansy => "Tansy",
            Prefix::Tawny => "Tawny",
            Prefix::Tempest => "Tempest",
            Prefix::Thistle => "Thistle",
            Prefix::Thorn => "Thorn",
            Prefix::Thrift => "Thrift",
            Prefix::Thrush => "Thrush",
            Prefix::Thunder => "Thunder",
            Prefix::Thyme => "Thyme",
            Prefix::Tiger => "Tiger",
            Prefix::Timber => "Timber",
            Prefix::Tiny => "Tiny",
            Prefix::Toad => "Toad",
            Prefix::Torn => "Torn",
            Prefix::Tremble => "Tremble",
            Prefix::Trickle => "Trickle",
            Prefix::Trout => "Trout",
            Prefix::Tuft => "Tuft",
            Prefix::Tulip => "Tulip",
            Prefix::Tumble => "Tumble",
            Prefix::Turtle => "Turtle",
            Prefix::Valley => "Valley",
            Prefix::Vine => "Vine",
            Prefix::Vixen => "Vixen",
            Prefix::Wasp => "Wasp",
            Prefix::Weasel => "Weasel",
            Prefix::Web => "Web",
            Prefix::Weed => "Weed",
            Prefix::Weevil => "Weevil",
            Prefix::Wet => "Wet",
            Prefix::Wheat => "Wheat",
            Prefix::Whimsy => "Whimsy",
            Prefix::Whirl => "Whirl",
            Prefix::Whisker => "Whisker",
            Prefix::Whisper => "Whisper",
            Prefix::Whispering => "Whispering",
            Prefix::Whistle => "Whistle",
            Prefix::Whorl => "Whorl",
            Prefix::Wild => "Wild",
            Prefix::Willow => "Willow",
            Prefix::Wind => "Wind",
            Prefix::Wing => "Wing",
            Prefix::Wish => "Wish",
            Prefix::Wisteria => "Wisteria",
            Prefix::Wolf => "Wolf",
            Prefix::Wolverine => "Wolverine",
            Prefix::Wood => "Wood",
            Prefix::Worm => "Worm",
            Prefix::Wren => "Wren",
            Prefix::Yarrow => "Yarrow",
            Prefix::Yew => "Yew",
            Prefix::Zinnia => "Zinnia",
        };
        write!(f, "{}", prefix_str)
    }
}

